---

latest:
  image: rust:latest
  stage: test
  script:
    - SHELL=/bin/bash cargo test

sync:
  image: ubuntu:18.04
  stage: deploy
  script:
    - 'apt-get update -y && apt-get install openssh-client git -y'
    - eval $(ssh-agent -s)
    - echo "$SSH_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh-add -l
    - git remote add github git@github.com:nsg/outline-mirror.git
    - git push -u github master
