---

latest:
  image: rust:latest
  stage: test
  script:
    - SHELL=/bin/bash cargo test

sync:
  image: ubuntu:18.04
  stage: deploy
  script:
    - 'apt-get update -y && apt-get install openssh-client git -y'
    - eval $(ssh-agent -s)
    - echo "$SSH_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan github.com > ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
    - git remote add github git@github.com:nsg/outline-mirror.git
    - echo "# This is a mirror" > README.md
    - echo "This is a mirror of https://gitlab.com/nsgb/outline" >> README.md
    - git config --global user.email "nsgb-ci@gitlab.local"
    - git config --global user.name "GitLab CI"
    - git add README.md && git commit -m "Overwrite README with mirror info"
    - git push github
  only:
    - master
